// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.AppView = (function(_super) {
  __extends(AppView, _super);

  function AppView() {
    return AppView.__super__.constructor.apply(this, arguments);
  }

  AppView.prototype.template = _.template('<button class="hit-button">Hit</button> <button class="stand-button">Stand</button> <button class="reset-button">New Deal</button> <div class="player-hand-container"></div> <div class="dealer-hand-container"></div>');

  AppView.prototype.events = {
    'click .hit-button': function() {
      return this.hit();
    },
    'click .stand-button': function() {
      return this.stand();
    },
    'click .reset-button': function() {
      return this.reset();
    }
  };

  AppView.prototype.initialize = function() {
    this.model.get('playerHand').on('playerLose', (function(_this) {
      return function() {
        return _this.lose();
      };
    })(this));
    this.model.get('dealerHand').on('playerWin', (function(_this) {
      return function() {
        return _this.win();
      };
    })(this));
    this.model.get('dealerHand').on('playerLose', (function(_this) {
      return function() {
        return _this.lose();
      };
    })(this));
    this.model.get('dealerHand').on('tie', (function(_this) {
      return function() {
        return _this.tie();
      };
    })(this));
    this.render();
    return this.buttonclicks = true;
  };

  AppView.prototype.render = function() {
    this.$el.children().detach();
    this.$el.html(this.template());
    this.$('.player-hand-container').html(new HandView({
      collection: this.model.get('playerHand')
    }).el);
    return this.$('.dealer-hand-container').html(new HandView({
      collection: this.model.get('dealerHand')
    }).el);
  };

  AppView.prototype.stand = function() {
    if (this.buttonclicks) {
      return this.model.get('dealerHand').stand(this.model.get('playerHand'));
    }
  };

  AppView.prototype.hit = function() {
    if (this.buttonclicks) {
      return this.model.get('playerHand').hit();
    }
  };

  AppView.prototype.win = function() {
    var node;
    node = $('<span></span>').text("PLAYER WINS").addClass("outcome");
    this.$el.append(node);
    return this.buttonclicks = false;
  };

  AppView.prototype.lose = function() {
    var node;
    node = $('<span></span>').text("PLAYER LOSES").addClass("outcome");
    this.$el.append(node);
    return this.buttonclicks = false;
  };

  AppView.prototype.tie = function() {
    var node;
    node = $('<span></span>').text("TIE GAME").addClass("outcome");
    this.$el.append(node);
    return this.buttonclicks = false;
  };

  AppView.prototype.reset = function() {
    $('body').find('.blackjack').html('');
    return new AppView({
      model: new App()
    }).$el.appendTo('.blackjack');
  };

  return AppView;

})(Backbone.View);
