// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.AppView = (function(_super) {
  __extends(AppView, _super);

  function AppView() {
    return AppView.__super__.constructor.apply(this, arguments);
  }

  AppView.prototype.template = _.template('<button class="hit-button">Hit</button> <button class="stand-button">Stand</button> <div class="player-hand-container"></div> <div class="dealer-hand-container"></div>');

  AppView.prototype.events = {
    'click .hit-button': function() {
      return this.model.get('playerHand').hit();
    },
    'click .stand-button': function() {
      return this.model.get('dealerHand').stand(this.model.get('playerHand'));
    },
    'playerWin': function() {
      return this.win();
    },
    'playerLose': function() {
      return this.lose();
    },
    'tie': function() {
      return this.tie();
    }
  };

  AppView.prototype.initialize = function() {
    return this.render();
  };

  AppView.prototype.render = function() {
    this.$el.children().detach();
    this.$el.html(this.template());
    this.$('.player-hand-container').html(new HandView({
      collection: this.model.get('playerHand')
    }).el);
    return this.$('.dealer-hand-container').html(new HandView({
      collection: this.model.get('dealerHand')
    }).el);
  };

  AppView.prototype.win = function() {
    var node;
    console.log("won");
    node = $('<span></span>').text("PLAYER WINS");
    return this.$el.prepend(node);
  };

  AppView.prototype.lose = function() {
    var node;
    console.log("lost");
    node = $('<span></span>').text("PLAYER LOSES");
    return this.$el.prepend(node);
  };

  AppView.prototype.tie = function() {
    var node;
    console.log("tie");
    node = $('<span></span>').text("TIE GAME");
    return this.$el.prepend(node);
  };

  return AppView;

})(Backbone.View);
