// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.GraphView = (function(_super) {
  __extends(GraphView, _super);

  function GraphView() {
    return GraphView.__super__.constructor.apply(this, arguments);
  }

  GraphView.prototype.className = 'graph';

  GraphView.prototype.template = _.template('<div id="chart"></div>');

  GraphView.prototype.initialize = function() {
    var chart;
    this.render();
    return chart = c3.generate({
      bindto: '#chart',
      data: {
        columns: [['data1', 30, 200, 100, 400, 150, 250], ['data2', 50, 20, 10, 40, 15, 25]]
      }
    });
  };

  GraphView.prototype.render = function() {
    return (this.$el.html(this.template)).fadeIn(1000);
  };

  return GraphView;

})(Backbone.View);
