// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.Graph = (function(_super) {
  __extends(Graph, _super);

  function Graph() {
    return Graph.__super__.constructor.apply(this, arguments);
  }

  Graph.prototype.initialize = function(params) {
    var chart;
    chart = c3.generate({
      bindto: '#chart',
      data: {
        columns: [['data1', 30, 200, 100, 400, 150, 250], ['data2', 50, 20, 10, 40, 15, 25]]
      }
    });
    return console.log(chart);
  };

  return Graph;

})(Backbone.Model);
